### ISSUE TITLE
General Issues with the project

### ISSUE THREAD

**Issue by Viciouss** [miniwolf/Game#18]
There are several points currently that make it very unattractive/painful for others to use or contribute to this project. It's even difficult for others to figure out the project structure and how to navigate it to just learn from what you do here because it's specific to the IDE you use.

This is why build systems like maven or gradle are so good, it's immediately clear where to look for everything that you need to know, how to build the project, how to run the test and where to adjust something in case of problems (if it is part of the build process of course). The structure is not coupled to an IDE but always the same. Adjusting versions is a matter of changing a number and getting the right transitive dependencies is handled automatically without any further actions needed.

Also, keeping jars in your source tree is a major problem not only because the master is at 260 MB already, which makes checking out the repository a real pain, but also because they are scattered over all your modules and lwjgl doesn't even have versions attached which makes it even more difficult to manage.

All in all there is too much implicit knowledge that one needs to have to make use of the project. This should really be fixed.

The other thing is, do you want to manage the project if it grows or do you actually want to code and add new features? The management will become more difficult from day to day.

**Comment by miniwolf** [comment]
Everything you say here is correct. However, I don't want to solve this problem using gradle or maven, though it could in theory solve all issues. But it is a sickness of me working alone on this project.
What I want to do is generate the project files that makes it possible for any to set it up without having to build maven and resolve all the dependencies through that.
One could make a system that would basically "build" the project files. It could be written i java or scala, or even kotlin. This would be a binary that would glob files and bind together jar files, in a well written way.

**Comment by Viciouss** [comment]
So basically you want something like libgdx provides with their engine if I'm not mistaken. You can download the setup tool from their page (https://libgdx.badlogicgames.com/download.html) and it asks you the project name, the destination and which extensions to use and then creates a complete project structure that one can load in their IDE. After that, you want to provide some scripts/tooling that actually build and releases the project, is that right?

**Comment by miniwolf** [comment]
It sounds very similar yes. If people would want to only build a game using the SDK that it provides, I would be able to release that as a Jar file.
But for working on the engine code, I would prefer that kind of setup.
